### ISSUE TITLE
0 error frequently logged from client error logger

### ISSUE THREAD

**Issue by shilman** [meteorhacks/kadira#133]
I am logging client-side AJAX errors on my app, and am seeing the following error type from Kadira fairly frequently.

```
{
  "errorType": "AJAX",
  "browser": {
    "UA": "Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/40.0.2214.94 Safari/537.36",
    "platform": "Win32",
    "language": "en-us",
    "cookieEnabled": true
  },
  "details": {
    "xhrResponseText": "",
    "xhrStatusText": "0 error",
    "url": "https://engine.kadira.io/simplentp/sync",
    "responseHeaders": "",
    "responseTime": 4.511
  },
  "ipAddress": "XXXXXXX",
  "timestamp": {
    "$date": 1422927710810
  }
}
```

As far as I know, Kadira seems to be working great for me, so it may just be random networking errors that are safe to ignore. This issue is (1) for your information, and (2) also to know if there is anything alarming or anything I should be doing differently from my side.

Notes:
- I am using the latest version of Kadira (`2.17.4`) as of this posting
- I have seen this across several browsers, and different IP clients
- My APP_ID is `Rc9Kx7vcgZiZory44`

Many thanks for creating a wonderful service!!!

**Comment by arunoda** [comment]
This is safe to ignore. This is an time sync request to capture errors with
correct time.

Btw: we have add some ratelimits. That might be the issue.

How many average amount of users you have for a minute?

I will check more.

**Comment by shilman** [comment]
Thanks for your fast response. I have very few users (< 10 simultaneous for now) but these errors are currently my most frequent error so I wanted to dig a little just in case.

If it is helpful for me to instrument anything to help you improve Kadira, please let me know. Otherwise, I will just ignore those errors.

Much appreciated!!!

**Comment by arunoda** [comment]
These can be ignored. You can also turn off our client side error tracking
to stop this ping.

**Comment by arunoda** [comment]
I am on the road now. Do a google check Kadira error tracking and you will
get how to stop client error tracking.

**Comment by shilman** [comment]
Thanks so much--I'll post again if I run into any issues.

**Comment by arunoda** [comment]
Great.

**Comment by shilman** [comment]
BTW, I did not know that Kadira has error tracking built in!!! That's so awesome. The errors I was mentioning were from my own error tracker that hooks into `window.onerror` and `$(document).ajaxError`. Your errors and summary are far more useful. In case it was not clear before -- this "0 error" is being tracked by my error logger not yours. I don't think it changes the outcome of the conversation, but I just wanted to be clear.

Many thanks!!
