### ISSUE TITLE
Maximum Call Stack Size Exceeded Error

### ISSUE THREAD

**Issue by bsbechtel** [meteorhacks/kadira#135]
I got the following error:

RangeError: Maximum call stack size exceeded
=> Exited with code: 7

I ended up changing the code because it was redundant anyways, but I figured this might be worth reporting. Here is what my code was inside a Meteor method that caused the error:

    Jobs.update(job_id, {$set: job_request});
    var job_id = Jobs.find(job_id);

    
    return { 
      message: "Your changes have been submitted. We will notify you if there are any issues.",
      job_id: job_id
    };

**Comment by arunoda** [comment]
Actually, it's not a Kadira error. It should happen without Kadira as well.

This is because you have returned a cursor which cannot stringify.

**Comment by bsbechtel** [comment]
Ah that makes sense. I guess it can be closed then. Thanks!
