### ISSUE TITLE
Error: Meteor code must always run within a Fiber. Try wrapping callbacks that you pass to non-Meteor libraries with Meteor.bindEnvironment.

### ISSUE THREAD

**Issue by chhib** [meteorhacks/kadira#137]
After upgrading Kadira

    meteorhacks:kadira              upgraded from 2.17.4 to 2.18.1

I get this:

    Kadira: completed instrumenting the app
    Kadira: successfully authenticated
    (STDERR) Error: Meteor code must always run within a Fiber. Try wrapping callbacks that you pass to non-Meteor libraries with Meteor.bindEnvironment.
    (STDERR)     at Object.Meteor._nodeCodeMustBeInFiber (packages/meteor/dynamics_nodejs.js:9:1)
    (STDERR)     at [object Object]._.extend.get (packages/meteor/dynamics_nodejs.js:21:1)
    (STDERR)     at withoutInvocation (packages/meteor/timers.js:4:1)
    (STDERR)     at bindAndCatch (packages/meteor/timers.js:13:1)
    (STDERR)     at Object._.extend.defer (packages/meteor/timers.js:68:1)
    (STDERR)     at packages/meteorhacks:kadira/lib/kadira.js:83:1
    (STDERR)     at Object.Meteor.startup (packages/meteor/startup_server.js:6:1)
    (STDERR)     at packages/meteorhacks:kadira/lib/kadira.js:80:1
    (STDERR)     at packages/meteorhacks:kadira/lib/kadira.js:146:1
    (STDERR)     at Request._callback (packages/meteorhacks:kadira/lib/kadira.js:337:1)

I get the same with just creating the todos example, adding `meteorhacks:kadira`, and creating the standard `server/kadira.js` with a Startup connect.

**Comment by arunoda** [comment]
wait. I'm working on a fix.

**Comment by arunoda** [comment]
Okay. try updating now. Published a fix.

**Comment by chhib** [comment]
Thanks, it is now working!

**Comment by arunoda** [comment]
Great.
