### ISSUE TITLE
can't uninstall kadira

### ISSUE THREAD

**Issue by dasmodel** [meteorhacks/kadira#138]
After removing kadira via `meteor remove meteorhacks:kadira`, my app no longer works:
```
/Users/me/.meteor/packages/meteor-tool/.1.0.38.1v7ejbf++os.osx.x86_64+web.browser+web.cordova/meteor-tool-os.osx.x86_64/dev_bundle/server-lib/node_modules/fibers/future.js:173
            throw(ex);
                  ^
ReferenceError: Kadira is not defined
    at app/server/kadira.js:1:36
    at app/server/kadira.js:3:3
    at /Users/me/src/packaging/.meteor/local/build/programs/server/boot.js:175:10
    at Array.forEach (native)
    at Function._.each._.forEach (/Users/me/.meteor/packages/meteor-tool/.1.0.38.1v7ejbf++os.osx.x86_64+web.browser+web.cordova/meteor-tool-os.osx.x86_64/dev_bundle/server-lib/node_modules/underscore/underscore.js:79:11)
    at /Users/me/src/packaging/.meteor/local/build/programs/server/boot.js:86:5
Exited with code: 8
Your application is crashing. Waiting for file change.
```

**Comment by dasmodel** [comment]
whoops, forgot to delete kadira.js

**Comment by arunoda** [comment]
Okay.

**Comment by arunoda** [comment]
BTW: Why are you removing it?
Is there any issues with that. May be we can fix them :)

**Comment by dasmodel** [comment]
Well I'm actually in the throes of trying to debug an issue with the spiderable package (I keep seeing an error about 'Meteor code must always run within a Fiber') and am uninstalling packages to see if it changes anything

**Comment by arunoda** [comment]
Okay. We did some bug fixes lately.
Make sure you are running the latest version of Kadira :)

**Comment by dasmodel** [comment]
Hi — I finally found the source of the bug and it's actually related to a diff. library of yours: meteorhacks:npm. When I remove the npm-container the fibers/spiderable error goes away but I can no longer use npmRequire which i really need. Do you have any ideas how to fix?
