### ISSUE TITLE
Error with kadira and new RC

### ISSUE THREAD

**Issue by caioreis** [meteorhacks/kadira#141]
Hi, I was testing my app using kadira and then I updated to 1.0.4, and this happend:

W20150310-00:48:19.327(-3)? (STDERR)          
W20150310-00:48:19.327(-3)? (STDERR) /home/caio/.meteor/packages/meteor-tool/.1.0.42-rc.2.m5ehz++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/dev_bundle/server-lib/node_modules/fibers/future.js:245
W20150310-00:48:19.328(-3)? (STDERR) 						throw(ex);
W20150310-00:48:19.328(-3)? (STDERR) 						      ^
W20150310-00:48:19.381(-3)? (STDERR) TypeError: Cannot call method 'bind' of undefined
W20150310-00:48:19.381(-3)? (STDERR)     at [object Object].MongoInternals.RemoteCollectionDriver.open (packages/meteorhacks:collection-utils/index.js:5:1)
W20150310-00:48:19.381(-3)? (STDERR)     at [object Object].open (packages/meteorhacks:kadira/lib/hijack/db.js:11:1)
W20150310-00:48:19.381(-3)? (STDERR)     at [object Object].Mongo.Collection (packages/mongo/collection.js:104:1)
W20150310-00:48:19.382(-3)? (STDERR)     at new Mongo.Collection (packages/dburles:mongo-collection-instances/mongo-instances.js:5:1)
W20150310-00:48:19.382(-3)? (STDERR)     at exposeMongoLivedata (packages/meteorhacks:meteorx/lib/mongo-livedata.js:3:1)
W20150310-00:48:19.382(-3)? (STDERR)     at packages/meteorhacks:meteorx/lib/server.js:21:1
=> Exited with code: 8

**Comment by caioreis** [comment]
Just to note, without the package it runs fine.
=

**Comment by arunoda** [comment]
Okay. Let me see what going on here.

**Comment by arunoda** [comment]
Okay. Seems like you are using meteorhacks:aggregate.

So, I've made some fixes for that.
Update like this:

~~~shell
meteor refresh
meteor update meteorhacks:aggregate
~~~

> Make sure you've meteorhacks:aggregate@1.2.0

Let me know how this works.

**Comment by caioreis** [comment]
@arunoda, it is working fine now! Thanks!

**Comment by arunoda** [comment]
Awesome.
