### ISSUE TITLE
Several "whitelist" errors in xcode log 

### ISSUE THREAD

**Issue by miri-am** [meteorhacks/kadira#148]
```ERROR whitelist rejection: url='https://engine.kadira.io/simplentp/sync'```
Meteor 1.05
Kadira 2.20.1

**Comment by arunoda** [comment]
Not sure.
May be you can whitelist https://engine.kadira.io
Frankly I don't know how to do it?

But, I'll give it a search.

**Comment by miri-am** [comment]
> Starting with Meteor 1.0.4 access rule for all domains and protocols (<access origin="*"/>) is no longer set by default due to certain kind of possible attacks.

Source: http://docs.meteor.com/#/full/App-setPreference

`App.accessRule("https://engine.kadira.io/*", false);` solves the issue.

**Comment by arunoda** [comment]
I think, we should mention this somewhere for others. What do you think?

**Comment by miri-am** [comment]
Definitely.
