### ISSUE TITLE
Content-Security-Policy and https://engine.kadira.io

### ISSUE THREAD

**Issue by dotnetwise** [meteorhacks/kadira#149]
If your app has custom Content-Security-Policy headers which is not "generated" by meteor then this will fail

```
Refused to connect to 'https://engine.kadira.io/errors' because it violates the following Content Security Policy directive: "
```

1. Are there many more domains to be added to the white-list?
2. Why aren't they being sent from Meteor's server side (first) and if it fails try to send from the client side?

**Comment by arunoda** [comment]
This is the only domain.
We don't need to route client side error with your meteor app.
That's why we are directly sending it to Kadira.

**Comment by dotnetwise** [comment]
I have added this but now I'm getting:
XMLHttpRequest cannot load https://engine.kadira.io/simplentp/sync. A wildcard '*' cannot be used in the 'Access-Control-Allow-Origin' header when the credentials flag is true. Origin 'http://meteor.local' is therefore not allowed access

**Comment by dotnetwise** [comment]
What if the connection/internet is down? 
Will it send it when it will first time resume?

**Comment by arunoda** [comment]
Yes it is.
this is a time sync machanism and it'll run again every one minute.

**Comment by dotnetwise** [comment]
So what about the above error?

**Comment by arunoda** [comment]
That's what I am figuring out.
Is there anyway, we can replicate this error locally?

**Comment by dotnetwise** [comment]
Yes create a meteor app and on the html file put this:
```
<head>
<meta http-equiv="Content-Security-Policy" content="default-src 'self' 'unsafe-inline' 'unsafe-eval' gap: content: data: http://localhost:3000 https://engine.kadira.io https://www.google-analytics.com http://meteor.local file:;" />
</head>
<body>
</body>
```
Then browse the app and look into the console

**Comment by dotnetwise** [comment]
Hmm, I have tried myself, but could not reproduce, however on the real app is still happening.

I think it doesn't have to do with `Content-Security-Policy` but instead with your server's `CORS`

So as I said before, please try this:
> I think, since you're implementing CORS, and you want to work with any domain, then in the `Access-Control-Allow-Origin:*` header you should actually have the origin domain (e.g. the Request Header `Origin` i.e. `Origin:http://meteor.local`
`Access-Control-Allow-Origin:http://meteor.local`

**Comment by arunoda** [comment]
Good call. Let me work on that.

**Comment by dotnetwise** [comment]
Sure. Btw, I see now kadira client side is posting to `https://engine.kadira.io/errors` every 1 minute or so, even though there is nothing to be posted e.g. no new errors.

In terms of saving user's battery, could we only do this if there are `pending` errors to be sent?

Also, is making chrome network requests too verbose e.g. after letting it there for 30m you'll have a huge bunch of `reporting no error` calls

**Comment by arunoda** [comment]
hmm. That's weird.
I'll also check on that.

**Comment by arunoda** [comment]
I've updated the CORS setup in our server. It'll work now.

**Comment by dotnetwise** [comment]
Works like a charm!

Now, let's see why so many requests :)

**Comment by arunoda** [comment]
We don't send errors if there are no errors.
Is it still happening? I guess it's trying to report the previous error.

**Comment by dotnetwise** [comment]
Yes, still happening, but at a lower frequence e.g. about 5-8 min

**Comment by arunoda** [comment]
Okay.

**Comment by dotnetwise** [comment]
Thank you!
