### ISSUE TITLE
... cannot load https://engine.kadira.io/simplentp/sync. No 'Access-Control-Allow-Origin'...

### ISSUE THREAD

**Issue by fungilation** [meteorhacks/kadira#152]
About a dozen lines like this on console.log after leaving my app idle on Chrome:
```
(index):1 XMLHttpRequest cannot load https://engine.kadira.io/simplentp/sync. No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'http://clubch.at' is therefore not allowed access. The response had HTTP status code 522.
```

This I assume is fixed by adding this to mobile-config.js. Not something that can be transparently added by the kadira package?
```
App.accessRule('*kadira.io');
```

**Comment by arunoda** [comment]
Good one. I should invest into more on this.

**Comment by fungilation** [comment]
FYI, the dozen logs are spread over only a window of 20 minutes, while I've left my app idling for hours.

**Comment by arunoda** [comment]
Actually, our server had some issues with the CORS setup.
Try now. I've updated that.

**Comment by fungilation** [comment]
I haven't seen a similar error in console while my app been idling in browser. I'm closing unless I see it again. Thanks!

**Comment by arunoda** [comment]
Great. Ping me back if you find something similar again.

**Comment by Streemo** [comment]
I found a similar error with enginex.kadria.io, on my cordova app. I believe adding the accessRule will solve it for me.

**Comment by allanalexandre** [comment]
This has happened to me, after inserting app. accessRule ("*://* kadira.io/*");

solved for me
