### ISSUE TITLE
Syntax-Error engine.kadira.io/simplentp/sync

### ISSUE THREAD

**Issue by funkybunky** [meteorhacks/kadira#153]
I get this error in the console of my app as well as the console of Kadira app.
If I try to inspect it, there is just one line and a number (no code).
Kadira seems to work, but the browser freezes for some seconds if I switch metrics (for example from "dashboard" to "pub/sub") and sometimes I get a warning message from firefox because of that (to stop the script)

**Comment by arunoda** [comment]
That's pretty weird.
What's your OS and the browser.

I'd like to see the error message on the log as well.

**Comment by funkybunky** [comment]
OS: Ubuntu 14.04
browser: latest Firefox (36.0.4)
just tried it with Chromium and got no error there and the site works very fluid without any lag.
after that I disabled every firefox addon but the error persisted. 
when I click on one of the errors in the app, I just get a new window called "sourcecode of [filename I provided]" and in the window is just this number: 1428348463340 (app) and in Kadira it's this number: 1428348558325. checking back to the app, there now also is the same number: 1428348558325
given that it works in chromium, I really don't need a fix here, especially if no one else seems to have such a problem. should I close the issue?
oh, and thank you very much for your contributions, Arunoda! :)

**Comment by arunoda** [comment]
Thanks.
If you found again let me know.
We had a few places with `debugger` keyword. I removed them after you've reported.
But, I don't think that's the issue.
Yeah we can close this for now.

**Comment by pburke** [comment]
Just chiming in to say that I experience this error too, also on Firefox in Ubuntu. Doesn't seem to affect my app at all, but the error pops up every few minutes in the browser console.

**Comment by rgm** [comment]
I'm also seeing this in Mac Firefox 36.0.4 / Meteor 1.0.3.2 / meteorhacks:kadira 2.20.1, server is an Ubuntu 14.04 bundled production instance sitting behind nginx. Not seeing it at all in Chrome, and I'm not seeing it in local dev.

![screen_shot_2015-04-16_at_14_18_20](https://cloud.githubusercontent.com/assets/6805/7191586/a91318fe-e443-11e4-9d11-3597098a92c2.png)

**Comment by arunoda** [comment]
Thanks all.
This is for our timesync algorithm. We didn't set a content-type for the response. (which is a timestamp).
So, firefox infer the content-type as xml and that's why we got a syntax error issue on Firefox.

Chrome does not infer content type and that's why there was no issue.

We've fixed this issue by adding a proper content type and now it works pretty well in both FF and other browsers. **You don't need to anything.**

**Comment by pburke** [comment]
Thanks for your quick work, Arunoda!

**Comment by arunoda** [comment]
Great. I'll close this now.

**Comment by rgm** [comment]
Great, thank you! Confirmed for me in FF 36.0.4 with no change at all to our production instance.
