### ISSUE TITLE
Exception from sub meteor_autoupdate_clientVersions id cswHfR4cnQmrEYZaB TypeError: Property 'check' of object #<Object> is not a function

### ISSUE THREAD

**Issue by sasikanth513** [meteorhacks/kadira#160]
I'm getting these errors in my server console from this morning

My app is not connected to kadira but the package is added to project.

I upated to the latest version of kadira which is 2.20.6
![kadira](https://cloud.githubusercontent.com/assets/6153816/7703674/2eb8ccc4-fe57-11e4-83c9-48954b44fc46.png)

![bts](https://cloud.githubusercontent.com/assets/6153816/7703684/43e8a8a8-fe57-11e4-8d5a-22d7a0f6db1c.png)

**Comment by arunoda** [comment]
Is this happens after you have installed Kadira or happens even after that.

It's hard to tell at a glance. I will have a look at it.

What's your meteor version of this app?

**Comment by sasikanth513** [comment]
This happens before and after the update of package.

No hurries.

**Comment by sasikanth513** [comment]
My issue is I'm using check as gloabal value in my custom publication, like below

```
var handle = Questions.find({},{sort: {askedAt: -1}, limit: 20}).observeChanges({
    added: function (id, fields) {
    	var question = _.extend(fields, {_id: id});        
        if( question.favs && question.favs.length > 0 ){
          check = _.some( question.favs , function( el ) {
               return el.user_id === self.userId;
           })
});
``` 

Sorry totally my fault closing the issue

**Comment by arunoda** [comment]
Okay. Got it.
