### ISSUE TITLE
kadira DOES seem to report from localhost

### ISSUE THREAD

**Issue by SierraGolf** [meteorhacks/kadira#166]
when I am running acceptance tests locally with the same kadira configuration as I have for production, I see it affecting the production app on kadira.

e.g. client errors appear in the error section and show ```Url: http://localhost:3000```

from what I read in the documentation/faq this should not be the case.

**Comment by arunoda** [comment]
You can use env. variables or Meteor Settings to avoid connecting to kadira
locally.
See: https://kadira.io/academy/getting-started-with-kadira/#auto-connect

That's solve this.

**Comment by SierraGolf** [comment]
ok, so I guess I miss-understood the FAQ. thanks for the quick help!

**Comment by arunoda** [comment]
Great.

**Comment by SierraGolf** [comment]
one last related question. what is the recommended way to differentiate staged version of the same app?

through different kadira apps, e.g.:
* my awesome app (prod)
* my awesome app (staging)

or is there a way to categorise the same app through some type of flags?

**Comment by arunoda** [comment]
Using different apps. That's everyone does.
