### ISSUE TITLE
How do I run Kadira locally?

### ISSUE THREAD

**Issue by omeid** [meteorhacks/kadira#170]
First let me clarify that I have no problem with paying and supporting projects that make my life as developer or in general easier, specially when it comes to opensource.

But currently I am working on a project with a lot of legal complexities and I can not share any sort of data with a 3rd party provider.

Reading though some discussion on pricing issue and open source alternatives it was mentioned that Kadira is open source. So if I want to use Kadira locally, how do I go about it?
I don't see any documentation or matter of fact, any "server" code.

Please advise.

**Comment by arunoda** [comment]
Hi,

Kadira's tracking code is open source. I understand it's sometimes harder
to send data outside.

Currently we don't have any details docs on Kadira data protocol and Apis.
We are rapidly changing it. That's why it's not documented yet.

**Comment by omeid** [comment]
Do you provide any Enterprise/in-house option? prebuilt EC2 instances would be nice.

**Comment by arunoda** [comment]
Yes. We've plans for this later this year.
What's your timeline requirements?

**Comment by omeid** [comment]
I have hard deadlines within few months. So timeline requirements are pretty tough.

Is your Enterprise edition just a plan for now or work in progress? any rough pricing?

**Comment by arunoda** [comment]
Pricing will be similar to Github Enterprise and it's yearly based planning.
We provide a kadira UI+tools installed docker image(s).
Send me an email (arunoda at kadira.io) to discuss more on this.
