### ISSUE TITLE
Disable Kadira Locally

### ISSUE THREAD

**Issue by patrickml** [meteorhacks/kadira#172]
Is there a way to disable Kadira locally using an ENV

Like 

`DISABLE_KADIRA=1 meteor --settings settings.json`

My use case is that I don't want to have to change my settings file for local and production, but I want to be able to see the avg usage on Kadira without the my MBP skewing the numbers.

**Comment by arunoda** [comment]
So, why don't you use env. vars to send kadira settings.
Only in the production.

**Comment by patrickml** [comment]
+1 thats a good question... Thank you that worked out.

If I set `KADIRA_OPTIONS_HOSTNAME` in mup it should propagate through to Kadira correct?

**Comment by arunoda** [comment]
Yes.

**Comment by patrickml** [comment]
Okay great. Il wait an hour and see if it changes so far the new host names have not shown up

http://cl.ly/image/0R1d0b2Q2L2c
