### ISSUE TITLE
Rest API how to enable kadira to work?

### ISSUE THREAD

**Issue by dmitrijs-balcers** [meteorhacks/kadira#176]
So for several reasons, I have to develop REST api using Meteor.JS and everything is great, but I'm not able to enable the kadira monitoring. Thought maybe someone have any idea.

So basically I'm trying to wrap existing Meteor.methods in rest API. It looks like this:

```
Router.route('methods/stages/getAandB/:id', {where: 'server'})
    .get(_getAandB);

function _getAandB(req, res) {

    Meteor.call('Stages.getAandB', req.someId, this.params.id, function (err, response) {
        if (err) {
            res.writeHead(err.error, {'Content-Type': 'application/json'});
            res.end(JSON.stringify(err));
        } else {
            res.writeHead(200, {'Content-Type': 'application/json'});
            res.end(JSON.stringify(response));
        }
    });
}
```

Can somebody explain me why kadira is not registering a Meteor.call('Stages.getAandB') ? And how can I make kadira to work?

Thank you.

**Comment by arunoda** [comment]
Could you elaborate more on this ? What do you mean by that?

Need to track rest Apis or need some rest API access to Kadira data.

**Comment by dmitrijs-balcers** [comment]
So basically what I'm trying to do, is to create a REST API using Meteor.
Due to REST API is very simple I decided to stick with Iron router (at allows to create RESTful API's).

To access data, I'm creating a meteor method, which basically may update, insert, delete or find document from DB. To make it restful I simply wrap it like described in comment above.

The problem is that, when I'm calling GET /methods/stages/getAandB/:id
Meteor.call('Stages.getAandB'); is not being represented in kadira UI. As well as if this meteor method will throw an error, it will not be represented in kadira errors tracking system as well.

**Comment by arunoda** [comment]
Yes you are correct. We don't track http Api context. We currently only
track DDP related stuff only.

We are planning to support this once we release our custom tracking API.
But not so soon.

**Comment by dmitrijs-balcers** [comment]
Yeah, but basically my REST api is calling Meteor DDP method (which is defined within the same package). Shouldn't it be tracked by kadira?

**Comment by dmitrijs-balcers** [comment]
Got my answer here #178
