### ISSUE TITLE
No pub/sub data available for my angular-meteor project

### ISSUE THREAD

**Issue by lscordilis** [meteorhacks/kadira#180]
I have no pub/sub data available for my Meteor project. I'm using the latest build of Angular-meteor and this is my first time using Kadira, so I'm not sure if this is a recent problem or if you guys just don't fully support angular-meteor in your frameworks yet. 

** also on the dashboard, "Reponse" should probably be "Response" ;) 

Otherwise, great work! Really liking the app so far

**Comment by arunoda** [comment]
We are having some data aggregation issue and we are working on it.
Sorry about the issue.

**Comment by lscordilis** [comment]
Great, thanks for the quick response!
