### ISSUE TITLE
Meteor 1.2-rc7 compatibility (method call hangs)

### ISSUE THREAD

**Issue by scsirdx** [meteorhacks/kadira#181]
Hello!

After updating my test project i got all meteor methods broken. Investigating this problem i found, that it happens when meteorhacks:kadira is installed.

How to reproduce: 
1. create new meteor project and add meteorhacks:kadira
2. add method
3. call it from client
or you can just add accounts-password + accounts-ui and it will not work with meteorhacks:kadira.

**Comment by moooji** [comment]
It seems that adding kadira also adds some other packages which might be the actual problem?

meteorhacks:kadira added, version 2.23.0
meteorhacks:meteorx added, version 1.3.1
mongo-livedata added, version 1.0.9-rc.0

**Comment by arunoda** [comment]
I just did a fix. Check the latest version: `2.23.1`.
It has the fix.

**Comment by moooji** [comment]
Confirmed, everything is working for me again!

**Comment by scsirdx** [comment]
@arunoda, everything is fine now. Thank you for quick response!

**Comment by arunoda** [comment]
Great!
