### ISSUE TITLE
Adding kadira to app, breaks it when using mup?

### ISSUE THREAD

**Issue by scarbies** [meteorhacks/kadira#184]
Kadira: successfully authenticated
{"line":"419","file":"webapp_server.js","message":"Error serving static file Error: EACCES, open '/opt/teamtime/app/programs/web.browser/9e6993ac55750ced99dcce4465dfa5c976e82f8b.js'","time":{"$date":1441052653217},"level":"error"}

after I remove kadira my app is working again...

**Comment by arunoda** [comment]
Hmm. Let's see.

**Comment by arunoda** [comment]
Hey, I tried with both Meteor 1.2 RC and all. Everything seems to work fine.
Try to add Kadira back. It'll work.

**Comment by scarbies** [comment]
I'll try again later. Seems like it was only an issue after deploying via mup. Maybe it was just co-incidence. Thanks @arunoda

**Comment by arunoda** [comment]
Okay.

**Comment by scarbies** [comment]
Sadly still an issue or compatibility problem with my app. As soon as I remove kadira the error log goes away.

**Comment by scarbies** [comment]
I removed the "kadira" section from settings.json and connected via code rather and it is now working.

**Comment by scarbies** [comment]
This was actually due to caching on CloudFlare, I believe!
