### ISSUE TITLE
Kadira: agent error: 404

### ISSUE THREAD

**Issue by rfines** [meteorhacks/kadira#186]
I am seeing the above error in my console now. Nothing has changed with my project setup but today when I started my app to begin working I saw this output:

    Kadira: successfully authenticated
    Kadira: agent error: 404

the agent error continues to be output to my console as the app continues to be run. I now have it in my console 10 times in the last few minutes of the app running.
Also it does not seem to matter if I use the newest version or an older version, the console output is the same either way.

**Comment by arunoda** [comment]
Hope this is fixed by now.
Had to reboot some servers.

**Comment by rfines** [comment]
This does appear to be fixed now. Thank you!

**Comment by lorensr** [comment]
@arunoda Happening to me in dev and production, meteor `1.2.0.1`, kadira `2.23.4`

**Comment by sferoze** [comment]
@arunoda Since upgrading to Meteor 1.2 this is happening all the time to me with on my local machine and production. Using kadira `2.23.4` as well.
