### ISSUE TITLE
Filtering sensitive data

### ISSUE THREAD

**Issue by FelipeRosa** [meteorhacks/kadira#189]
Is there a way to disable sending sensitive data, like credit card numbers, to kadira? Am I missing something?

**Comment by arunoda** [comment]
Yes we have.
Check this guide:
https://support.kadira.io/knowledgebase/articles/487222-how-to-protect-sensitive-information-for-security

**Comment by FelipeRosa** [comment]
Ah, alright. 

Thank you.

**Comment by arunoda** [comment]
No problem.

**Comment by chrise86** [comment]
How would I filter specific params that aren't tied to a collection? Looking at http://support.kadira.io/knowledgebase/articles/487222-how-to-protect-sensitive-information-for-security it looks like you can only filter all params, and only if tied to a collection.
