### ISSUE TITLE
Kadira Error Logging for Multiple Meteor Apps on Same Host

### ISSUE THREAD

**Issue by joncursi** [meteorhacks/kadira#192]
I have two Meteor apps running on the same host, but on different ports. They are identical. I deploy them with Meteor Up (thanks!) and authenticate with Kadira on deployment. When I deploy meteor app A, I see live data in that app's Kadira dashboard and errors are logged as well. When I deploy meteor app B, I see live data in that app's Kadira dashboard but errors are not logged (instead I see the information for updating kadira and adding zones -- it assumes i am using an outdated version of kadira or something is not configured properly, but the two apps are literally identical).

Is this a known limitation of the Kadira Error Logging feature? Error logging can only occur for one app on the host?

**Comment by arunoda** [comment]
May be that's because we've not received any error from App B. In Kadira,
apps are separate entities.

**Comment by joncursi** [comment]
What is the most appropriate way to pass errors on to Kadira? When I do `mup logs`, I see plenty of errors sitting in the logfiles but Kadira doesn't seem to catch wind of them.

**Comment by arunoda** [comment]
May be try to send a browser error.
Do this: open the app on the browser and apply this:

`setTimeout(function() {throw new Error("Oh!");});

**Comment by joncursi** [comment]
Thank you!

**Comment by arunoda** [comment]
Great.
