### ISSUE TITLE
Exception in queued task: TypeError: Object  has no method 'size'

### ISSUE THREAD

**Issue by brentjanderson** [meteorhacks/kadira#200]
This appears to be an error internal to Kadira, with more details available here: https://ui.kadira.io/et/699ef319-8b2d-473e-87c1-a44f1423763f/wrZXoP4tWKSzPvLmv

Below is the full error (repeated hundreds of times in my console) from Kadira:

```
Exception in queued task: TypeError: Object  has no method 'size'
I20151107-10:25:14.573(-7)?     at [object Object].proto._pollMongo (meteor://💻app/packages/meteorhacks_kadira/lib/hijack/wrap_observers.js:67:1)
I20151107-10:25:14.573(-7)?     at Object.task (meteor://💻app/packages/mongo/polling_observe_driver.js:85:1)
I20151107-10:25:14.573(-7)?     at [object Object]._.extend._run (meteor://💻app/packages/meteor/fiber_helpers.js:147:1)
I20151107-10:25:14.574(-7)?     at meteor://💻app/packages/meteor/fiber_helpers.js:125:1
```

I'm not sure where the unicode Laptop icon (💻) is coming from. Removing meteorhacks:kadira silences the error, and I haven't identified any other packages causing this issue for Kadira.

**Comment by arunoda** [comment]
Okay. What's the meteor version you are using ?
And can I have the package list?

**Comment by arunoda** [comment]
Try now. I did a fix.

**Comment by lukasvan3l** [comment]
yup, a `meteor update` fixed it for me! Thanks for the quick response :)

**Comment by brentjanderson** [comment]
This appears to have fixed the issue. Thanks!
