### ISSUE TITLE
Incorporate Mongo Explain

### ISSUE THREAD

**Issue by jbrozena22** [meteorhacks/kadira#202]
I have a feature request.

Our method for optimizing Meteor is as follows: 
1) Check out Kadira - identify slow method and subscriptions. Dig into a stack trace to figure out the underlying database query causing issues.
2) Log into the mongo shell, run the query with '.explain()' to determine whether the query was indexed.
3) Try to figure out where in the code that query was called from. Update the code, or add a database index

---
I would pay for the enterprise version if:
1) Kadira could automatically run .explain() on really slow queries (really slow queries would probably need a threshold). I understand this would need to be an on demand feature because the overhead would be too high if it was run on every query.
2) If the stack trace could point to the line in the code that was causing the problem that would be helpful. I'm sure there are constraints in figuring that out from the minified version.

Thanks so much - this tool is incredible and an absolute must have for Meteor projects.

**Comment by arunoda** [comment]
Thanks. We are working on a project called "Kadira Genie" which does a lot of tasks for you. Basically, with that you could reduce a lot of development/maintenance hours.

We'll launch it early next year. (Very soon).
