### ISSUE TITLE
Fails to add package (While checking for meteorhacks:kadira-binary-deps@1.2.1)

### ISSUE THREAD

**Issue by christophmayrhofer** [meteorhacks/kadira#209]
meteor add meteorhacks:kadira
 => Errors while adding packages:             
                                              
While checking for meteorhacks:kadira-binary-deps@1.2.1:
error: No compatible binary build found for this package. Contact the package author and ask them to publish it for your platform.

Here are my installed packages:

accounts-password                             1.1.4 
alanning:roles                                1.2.14  
aldeed:autoform                               5.8.1  
aldeed:autoform-select2                       2.0.2  
aldeed:collection2                            2.8.0  
aldeed:geocoder                               0.3.8  
aldeed:template-extension                     3.4.3* 
alon:ol3                                      3.11.2  
audit-argument-checks                         1.0.4  
autopublish                                   1.0.4  
blaze-html-templates                          1.0.1  
cfs:filesystem                                0.1.2  
cfs:graphicsmagick                            0.0.18+ 
cfs:gridfs                                    0.0.33  
cfs:standard-packages                         0.5.9  
check                                         1.1.0  
chhib:selectize-bootstrap-3                   0.0.1 
chrismbeckett:toastr                          2.1.2_1  
comerc:autoform-selectize                     2.2.4  
dburles:collection-helpers                    1.0.4  
ecmascript                                    0.1.6* 
erasaur:meteor-lodash                         3.10.1_1* 
es5-shim                                      4.1.14  
fortawesome:fontawesome                       4.5.0  
gwendall:autoform-i18n                        0.1.9_1 
gwendall:simple-schema-i18n                   0.2.1
gwendall:template-animations                  0.2.2  
harrison:papa-parse                           1.1.1 
insecure                                      1.0.4  
iron:router                                   1.0.12  
jeremy:geocomplete                            1.6.5_9  
jiku:bootstrap-toggle                         0.0.1  
jquery                                        1.11.4 
jss:flag-icon                                 0.7.3  
kidovate:bootstrap-slider                     0.0.5  
lbee:moment-helpers                           1.2.1* 
mdg:geolocation                               1.1.0* 
meteor-base                                   1.0.1  
meteoric:autoform-ionic                       0.1.6+
meteoric:ionic                                0.2.0 
meteoric:ionic-sass                           0.3.0  
meteoric:ionicons-sass                        0.1.7
michalvalasek:autoform-bootstrap-colorpicker  0.1.0  
mizzao:autocomplete                           0.5.1 
mizzao:bootboxjs                              4.4.0  
mizzao:jquery-ui                              1.11.4  
mizzao:user-status                            0.6.6  
mobile-experience                             1.0.1  
momentjs:moment                               2.11.1  
mongo                                         1.1.3  
moonco:pointer                                0.0.4  
mpowaga:autoform-summernote                   0.4.2  
multiply:iron-router-progress                 1.0.2  
natestrauser:select2                          3.5.1*
nikhizzle:session-bind                        1.0.2
numtel:cfs-image-resize                       0.0.1
ongoworks:security                            1.3.0  
peppelg:bootstrap-3-modal                     1.0.4
postrednik:meteor-rangeslider                 0.1.0  
reactive-dict                                 1.1.3  
reactive-var                                  1.0.6 
rzymek:moment-locales                         2.9.0 
sergeyt:typeahead                             0.11.1_8  
session                                       1.1.1  
softwarerero:accounts-t9n                     1.2.0* 
standard-minifiers                            1.0.2  
tap:i18n                                      1.7.0  
tap:i18n-ui                                   0.7.0  
tracker                                       1.0.9  
twbs:bootstrap                                3.3.6  
useraccounts:core                             1.13.1  
useraccounts:ionic                            1.13.1  
useraccounts:iron-routing                     1.13.1  
utilities:avatar                              0.9.2 
valedaemon:circular-progress                  1.0.0+ 
vimes1984:autoform-textangular                1.1.4  
yogiben:admin                                 1.2.4* 
yogiben:autoform-file                         0.4.2* 
yogiben:autoform-map                          0.2.0 
yogiben:autoform-modals                       0.3.8  
yogiben:data-binding                          0.0.0  
zimme:active-route                            2.3.2  
zimme:select2-bootstrap3-css                  1.4.6

**Comment by arunoda** [comment]
Do this:

meteor add meteorhacks:kadira@2.27.2

**Comment by christophmayrhofer** [comment]
Thank you. solved the problem and i love the stats :) Just one concern... How much server load does kadira itself cause when it is running in my meteor app?

**Comment by arunoda** [comment]
@christophmayrhofer less than 10%
