### ISSUE TITLE
I think Kadira is adding collections to my database with 0 documents but taking 50mb of space each.

### ISSUE THREAD

**Issue by sferoze** [meteorhacks/kadira#227]
In my database I have noticed the collections, _kdconfig, _kdtimeevents, _kdtraces. 

_kdtimeevents is taking up 50MB of space in compose.io yet the collections has 0 documents in it. 

_kdtraces is also taking up 50MB yet has 0 documents in it. 

What is going on?

**Comment by joadr** [comment]
I've got this too, It's too weird that it's that heavy without having any collection

**Comment by arunoda** [comment]
That's coming from Kadira Debug.
If you are not using Kadira Debug, just remove those collections.

**Comment by maxko87** [comment]
These collections cannot be deleted.

```
> show tables
__kdtimeevents
__kdtraces
> db.__kdconfig.drop()
E QUERY    [thread1] TypeError: db.__kdconfig is undefined
```

**Comment by maxko87** [comment]
Ah, turns out this is a known bug with Mongo and they encourage not to prefix collections with underscores. You can still remove like so: `db.getCollection("__kdtraces").drop()`

http://stackoverflow.com/questions/24309685/mongo-client-cant-access-collections-prefixed-with-an-underscore
