### ISSUE TITLE
Kadira stopped working. (period)

### ISSUE THREAD

**Issue by fvpDev** [meteorhacks/kadira#241]
Not sure if related to #240 but about 30 minutes ago started getting
`Kadira: authentication failed - check your appId & appSecret`
on meteor server log (no changes on my part).

Also https://ui.kadira.io/ giving `502 Bad Gateway: Registered endpoints failed to handle the request.`

**Comment by arunoda** [comment]
@fvpDev Yes. We had an DB related issue due to an Google could incident. I sent you an email regarding that.

Now, things came back to the normal stage and we are monitoring it for another few hours.
