### ISSUE TITLE
Errors are no longer showing up for my app but performance monitoring is still working.

### ISSUE THREAD

**Issue by mjgallag** [meteorhacks/kadira#242]
I have the latest version of this package `2.29.1` and the latest version of meteor `1.3.4.1`.

I tried restarted my app's container on galaxy and all looks good:
```
6s55 2016-07-06 14:04:05-07:00 Application process starting, version: 30 on apprunner mdg0/apprunner:20160606T225805Z_86c9deb
6s55 2016-07-06 14:04:19-07:00 Kadira: completed instrumenting the app
6s55 2016-07-06 14:04:19-07:00 Kadira: Successfully connected
```

But `throw new Error('TEST');` doesn't ever show up in Kadira.

Thanks in advance for your help @arunoda.

**Comment by arunoda** [comment]
How do you throw the error? Via browser console.
If so, try to do this like this:

```js
setTimeout(function() {
   throw new Error('TEST');
}, 0);
```

**Comment by mjgallag** [comment]
Ah ha, that works, thanks. Sorry for the false alarm, I thought it was a valid test to throw an error in browser console without the setTimeout.

I got a bit thrown off because I was fixing an unhandled  exception in an autoValue function of mine that AutoForm caught and wrote to console.error, but didn't then re-throw. I now understand that Kadira won't pick up console.error writes.
https://github.com/aldeed/meteor-autoform/blob/devel/autoform-events.js#L309
