### ISSUE TITLE
Putting hostname in __meteor_runtime_config__ makes Meteor autoupdate unstable

### ISSUE THREAD

**Issue by glasser** [meteorhacks/kadira#245]
Since #123, if you specify hostname explicitly (via `$KADIRA_OPTIONS_HOSTNAME`, options:hostname in settings, or hostname passed explicitly to Kadira.connect), the hostname will also go into `__meteor_runtime_config__`.

The contents of `__meteor_runtime_config__` are part of the hash used by default by Meteor to identify the client bundle: https://github.com/meteor/meteor/blob/devel/packages/webapp-hashing/webapp-hashing.js#L20

The autoupdate package makes Meteor try to reload if the server that the client connects to has a different value of the autoupdate versions than the initial app HTML.

This means that if you're using an explicit hostname and your app HTML and DDP come from different servers, you'll see your app reload.

Galaxy currently triggers this:
- To help support our users who use Kadira, Galaxy always sets `$KADIRA_OPTIONS_HOSTNAME`
- The current implementation of load-balanced sticky sessions sometimes allows the initial app HTML and subsequent websocket to be served from different backends (though once the websocket is served, you get a consistent backend).  And it appears that some configurations of Safari might not actually process set-cookie on websockets, so this is worse with Safari.

It seems like the best thing for Galaxy to do may be to stop setting KADIRA_OPTIONS_HOSTNAME.  But maybe it would make sense to make it possible to set a custom hostname without putting the hostname into the runtime config.  Does hostname-in-runtime-config only support this one small client error feature from #123?

**Comment by arunoda** [comment]
Okay. Makes sense.
I think we could remove that. 
We are not 100% using that feature either.

**Comment by arunoda** [comment]
I assume `v2.30.0` would fix this issue.

**Comment by glasser** [comment]
Thanks Arunoda! Looking forward to meeting you today.
