### ISSUE TITLE
Kadira crashes my app.

### ISSUE THREAD

**Issue by itshallrun** [meteorhacks/kadira#255]
Hi, 
I am using Meteor 1.4.1.1 and the actual version of kadira:debug
 + jalik:ufs

I get the following error after adding kadira:debug to my project.

`W20161115-01:16:11.489(1)? (STDERR) ufs: cannot set store permissions 0744 (EPERM: operation not permitted, chmod '/uploads/logo')
W20161115-01:16:11.775(1)? (STDERR) /Users/mca/.meteor/packages/meteor-tool/.1.4.1_1.1h0re2h++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/server-lib/node_modules/fibers/future.js:280
W20161115-01:16:11.775(1)? (STDERR) 						throw(ex);
W20161115-01:16:11.775(1)? (STDERR) 						^
W20161115-01:16:11.776(1)? (STDERR) 
W20161115-01:16:11.776(1)? (STDERR) TypeError: Cannot read property 'createDataHandler' of undefined
W20161115-01:16:11.776(1)? (STDERR)     at setLabels (packages/meteorhacks_kadira/packages/meteorhacks_kadira.js:3303:1)
W20161115-01:16:11.777(1)? (STDERR)     at packages/meteorhacks_kadira/packages/meteorhacks_kadira.js:2840:1
W20161115-01:16:11.777(1)? (STDERR)     at packages/meteorhacks_meteorx/packages/meteorhacks_meteorx.js:169:1
W20161115-01:16:11.779(1)? (STDERR)     at Array.forEach (native)
W20161115-01:16:11.780(1)? (STDERR)     at packages/meteorhacks_meteorx/packages/meteorhacks_meteorx.js:168:1`

The permission of 'uploads/logo/' are set to allow write and read for everyone. It works as long as kadira is not added to the project.

Please help.

**Comment by arunoda** [comment]
`kadira:debug` is doesn't support Meteor 1.4.x
BTW: It's not directly related to this project.

Try to remove `kadira:debug` from your project.
