### ISSUE TITLE
Cannot connect to application

### ISSUE THREAD

**Issue by DanceParty** [meteorhacks/kadira#261]
I am deploying my application to Azure using the Demeteorizer tool but when I try and connect to Kadira, there is no logging.

![image](https://cloud.githubusercontent.com/assets/10778294/26062717/82dedab6-3940-11e7-83b9-3ab928a55e30.png)

Also, this is what my settings.json looks like. Keep in mind, this configuration works locally, maybe I am missing something?

```
{   
  "database": {     
     "server"   : "*********.database.windows.net",     
     "database" : "********",     
     "user"     : "****",     
     "password" : "****",     
     "options"  : {       
        "encrypt" : true,       
        "appName" : "Test App"     
      }   
  },   
  "kadira": {     
     "appId": "********",     
     "appSecret": "*******-*****-*****-****-*******"   
  } 
}
```

Thanks in advance!

**Comment by merlinstardust** [comment]
Kadira shut down yesterday May 15 11.59 PM Pacific Time.

From an email Arunoda sent out

Hi there,

As we discussed earlier, we were supposed to shutdown by April. But with the [Meteor's acquisition of Kadira assets](https://blog.meteor.com/mdg-acquires-kadira-apm-96dfb3167fe5) we both have decided to keep it maintain for until May 15th.

So, we'll officially shutdown kadira.io service by May 15 11.59 PM Pacific Time.

We did not migrate accounts to Meteor's APM (a version of Kadira) and all the accounts (including payments) will be deleted. You can use use Meteor APM or open source version of Kadira if you need to continue using Kadira.

For more information, just reply to this email.
