### ISSUE TITLE
Provide dummy credentials for appId and appSecret

### ISSUE THREAD

**Issue by SkeLLLa** [meteorhacks/kadira#86]
Hello.

I'm using kadira for a long time and it works almost perfectly for me. But sometimes I want to prevent it form sending any data to kadira server (i.e. while developing). I don't want to disable it completely (i.e. with `if (Meteor.settings.env === 'development')`).

**Comment by evolross** [comment]
I've noticed that even when you don't provide `Meteor.settings` or environment variables credentials, Kadira still outputs: `Kadira: completed instrumenting the app` when you're in development which is kind of confusing/misleading.
