### ISSUE TITLE
Kadira crashes with Meteor.settings.kadira

### ISSUE THREAD

**Issue by DirkStevens** [meteorhacks/kadira#95]
Thought I'd follow some good practice and put the appId and appSecret in my settings.json:

```javascript
"kadira" : {
   "id": <abc>,
   "secret": <xyz>
}
```

then initialize on the server as follows:

```javascript
Meteor.startup(function() {
	Kadira.connect(Meteor.settings.kadira.id, Meteor.settings.kadira.secret);
});
```

but that crashes Kadira!

Renaming the setting to kadira_app works:

```javascript
Meteor.startup(function() {
	Kadira.connect(Meteor.settings.kadira_app.id, Meteor.settings.kadira_app.secret);
});
```

This happens also with the latest 2.11.2 release.

Here's the server log:

```javascript
W20141006-21:04:35.931(2)? (STDERR) /Users/dirkstevens/MadeWithWonder/surveymonkey/.meteor/local/build/programs/server/packages/meteorhacks_kadira.js:2951
W20141006-21:04:35.931(2)? (STDERR)     throw err;                                                                
W20141006-21:04:35.932(2)? (STDERR)           ^
W20141006-21:04:35.940(2)? (STDERR) Error: Kadira: required appId and appSecret
W20141006-21:04:35.940(2)? (STDERR)     at Object.Kadira.connect (packages/meteorhacks:kadira/lib/kadira.js:67)
W20141006-21:04:35.946(2)? (STDERR)     at commonErrRegExps (packages/meteorhacks:kadira/lib/auto_connect.js:15)
```

**Comment by ccorcos** [comment]
I'm confused. Whats the solution here?

**Comment by DanielDornhardt** [comment]
Hi @ccorcos , do you have the same problem?

The problem was I put empty strings into the kadira configuration section of my meteor settings and tried to configure kadira during runtime.

Just don't put an empty or example/dummy kadira configuration parameters into your settings.

**Comment by ccorcos** [comment]
ah. My problem is that I had "appId" and "secret" and was using Kadira.connect with those variables, but Kadira was trying to autoconnect and failing due to "appSecret"

**Comment by arunoda** [comment]
@DanielDornhardt  thanks for the quick help.
Yes @ccorcos That's why throw an error to avoid connecting to a wrong app.

**Comment by arunoda** [comment]
Anyway, I think this issue is okay to close.
I hope it's indexed by Google properly :)

**Comment by ccorcos** [comment]
I would clarify [here](https://github.com/meteorhacks/kadira#auto-connect) that "auto-connect" means that you do not have to call `Kadira.connect` if you have the setting specified.

This is actually a really sweet feature. I think I might do this for `ccorcos:neo4j` ;)

**Comment by arunoda** [comment]
Yes it is.
